version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - /opt/htpc/sonarr:/config
      - /DS1819/Video:/tv #optional
      - /DS1819/Downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:develop
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - /opt/htpc/radarr:/config
      - /DS1819/Video:/movies #optional
      - /DS1819/Downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - /opt/htpc/sabnzbd:/config
      - /DS1819/Downloads:/downloads #optional
      - /DS1819/Downloads/incomplete:/incomplete-downloads #optional
    ports:
      - 8080:8080
    restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr:nightly
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - /opt/htpc/lidarr:/config
      - /DS1819/Music:/music #optional
      - /DS1819/Downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped




